/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersettingsImport } from './routes/usersettings'
import { Route as SessionsImport } from './routes/sessions'
import { Route as PostsImport } from './routes/posts'
import { Route as AnalyticsImport } from './routes/analytics'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as SessionSessionIDImport } from './routes/session.$sessionID'
import { Route as AnalyticsAnalyticsIDImport } from './routes/analytics_.$analyticsID'
import { Route as AnalyticsAnalyticsIDGraphsImport } from './routes/analytics_.$analyticsID_.graphs'

// Create/Update Routes

const UsersettingsRoute = UsersettingsImport.update({
  id: '/usersettings',
  path: '/usersettings',
  getParentRoute: () => rootRoute,
} as any)

const SessionsRoute = SessionsImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRoute,
} as any)

const PostsRoute = PostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const AnalyticsRoute = AnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SessionSessionIDRoute = SessionSessionIDImport.update({
  id: '/session/$sessionID',
  path: '/session/$sessionID',
  getParentRoute: () => rootRoute,
} as any)

const AnalyticsAnalyticsIDRoute = AnalyticsAnalyticsIDImport.update({
  id: '/analytics_/$analyticsID',
  path: '/analytics/$analyticsID',
  getParentRoute: () => rootRoute,
} as any)

const AnalyticsAnalyticsIDGraphsRoute = AnalyticsAnalyticsIDGraphsImport.update(
  {
    id: '/analytics_/$analyticsID_/graphs',
    path: '/analytics/$analyticsID/graphs',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsImport
      parentRoute: typeof rootRoute
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsImport
      parentRoute: typeof rootRoute
    }
    '/usersettings': {
      id: '/usersettings'
      path: '/usersettings'
      fullPath: '/usersettings'
      preLoaderRoute: typeof UsersettingsImport
      parentRoute: typeof rootRoute
    }
    '/analytics_/$analyticsID': {
      id: '/analytics_/$analyticsID'
      path: '/analytics/$analyticsID'
      fullPath: '/analytics/$analyticsID'
      preLoaderRoute: typeof AnalyticsAnalyticsIDImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionID': {
      id: '/session/$sessionID'
      path: '/session/$sessionID'
      fullPath: '/session/$sessionID'
      preLoaderRoute: typeof SessionSessionIDImport
      parentRoute: typeof rootRoute
    }
    '/analytics_/$analyticsID_/graphs': {
      id: '/analytics_/$analyticsID_/graphs'
      path: '/analytics/$analyticsID/graphs'
      fullPath: '/analytics/$analyticsID/graphs'
      preLoaderRoute: typeof AnalyticsAnalyticsIDGraphsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/posts': typeof PostsRoute
  '/sessions': typeof SessionsRoute
  '/usersettings': typeof UsersettingsRoute
  '/analytics/$analyticsID': typeof AnalyticsAnalyticsIDRoute
  '/session/$sessionID': typeof SessionSessionIDRoute
  '/analytics/$analyticsID/graphs': typeof AnalyticsAnalyticsIDGraphsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/posts': typeof PostsRoute
  '/sessions': typeof SessionsRoute
  '/usersettings': typeof UsersettingsRoute
  '/analytics/$analyticsID': typeof AnalyticsAnalyticsIDRoute
  '/session/$sessionID': typeof SessionSessionIDRoute
  '/analytics/$analyticsID/graphs': typeof AnalyticsAnalyticsIDGraphsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/posts': typeof PostsRoute
  '/sessions': typeof SessionsRoute
  '/usersettings': typeof UsersettingsRoute
  '/analytics_/$analyticsID': typeof AnalyticsAnalyticsIDRoute
  '/session/$sessionID': typeof SessionSessionIDRoute
  '/analytics_/$analyticsID_/graphs': typeof AnalyticsAnalyticsIDGraphsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/posts'
    | '/sessions'
    | '/usersettings'
    | '/analytics/$analyticsID'
    | '/session/$sessionID'
    | '/analytics/$analyticsID/graphs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/posts'
    | '/sessions'
    | '/usersettings'
    | '/analytics/$analyticsID'
    | '/session/$sessionID'
    | '/analytics/$analyticsID/graphs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/posts'
    | '/sessions'
    | '/usersettings'
    | '/analytics_/$analyticsID'
    | '/session/$sessionID'
    | '/analytics_/$analyticsID_/graphs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  PostsRoute: typeof PostsRoute
  SessionsRoute: typeof SessionsRoute
  UsersettingsRoute: typeof UsersettingsRoute
  AnalyticsAnalyticsIDRoute: typeof AnalyticsAnalyticsIDRoute
  SessionSessionIDRoute: typeof SessionSessionIDRoute
  AnalyticsAnalyticsIDGraphsRoute: typeof AnalyticsAnalyticsIDGraphsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  PostsRoute: PostsRoute,
  SessionsRoute: SessionsRoute,
  UsersettingsRoute: UsersettingsRoute,
  AnalyticsAnalyticsIDRoute: AnalyticsAnalyticsIDRoute,
  SessionSessionIDRoute: SessionSessionIDRoute,
  AnalyticsAnalyticsIDGraphsRoute: AnalyticsAnalyticsIDGraphsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/admin",
        "/analytics",
        "/posts",
        "/sessions",
        "/usersettings",
        "/analytics_/$analyticsID",
        "/session/$sessionID",
        "/analytics_/$analyticsID_/graphs"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/admin": {
      "filePath": "admin.jsx"
    },
    "/analytics": {
      "filePath": "analytics.jsx"
    },
    "/posts": {
      "filePath": "posts.jsx"
    },
    "/sessions": {
      "filePath": "sessions.jsx"
    },
    "/usersettings": {
      "filePath": "usersettings.jsx"
    },
    "/analytics_/$analyticsID": {
      "filePath": "analytics_.$analyticsID.jsx"
    },
    "/session/$sessionID": {
      "filePath": "session.$sessionID.jsx"
    },
    "/analytics_/$analyticsID_/graphs": {
      "filePath": "analytics_.$analyticsID_.graphs.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
